<?php

namespace Mmm\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findAuthorCategories(User $user)
    {
        return $this->findBy(array(
            'createdBy' => $user
        ));
    }
}
