<?php

namespace Mmm\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Mmm\ApiBundle\Entity\User;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends EntityRepository
{
    public function findAuthorCategories(User $user, $offset = 0, $limit = 20)
    {
        return $this->findBy(array(
            'createdBy' => $user,
        ), array(), $limit, $offset);
    }
}
