<?php

namespace Mmm\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Mmm\ApiBundle\Entity\Place;
use Mmm\ApiBundle\Entity\User;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function findAuthorTasksByPlace(Place $place, User $user, $offset = 0, $limit = 20)
    {
        return $this->findBy(array(
            'place' => $place,
            'createdBy' => $user
        ), $offset, $limit);
    }
}
