<?php

namespace Mmm\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Mmm\FrontendBundle\Entity\User;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function findAuthorTasks(User $user)
    {
        return $this->findBy(array(
            'createdBy' => $user
        ));
    }
}
